package com.webank.weid.protocol.amop;

import java.util.Map;

import com.webank.wedpr.confidentialpayment.OwnerResult;
import lombok.Data;

import com.webank.weid.constant.CredentialType;
import com.webank.weid.protocol.amop.base.AmopBaseMsgArgs;
import com.webank.weid.protocol.base.PresentationE;

/**
 * @author tonychen 2020年2月6日
 */
@Data
public class RequestConsumableCredentialArgs extends AmopBaseMsgArgs {

    /**
     * user's credential list.
     */
    private PresentationE presentation;

    /**
     * user's ownerResult, generated by user's private key.
     */
    private OwnerResult ownerResult;

    /**
     * generated by verifier, related with policy id, target user weid, and challenge.
     */
    private String seqId;

    /**
     * original or zkp.
     */
    private CredentialType credentialType;

    /**
     * extra data which policy presenter can use it store some specific business data.
     */
    private Map<String, String> extra;
}
