package com.webank.weid.protocol.amop;

import com.webank.wedpr.confidentialpayment.proto.CreditCredential;
import lombok.Data;

import com.webank.weid.protocol.base.PresentationE;

/**
 * @author tonychen 2020年1月16日
 */
@Data
public class RequestTransferCreditCredentialArgs {

    /**
     * user's credential list, generated by verifier's policy.
     */
    private PresentationE presentation;

    /**
     * the consummable credential, has been transfered to verifier by user.
     */
    private CreditCredential creditCredential;
}
