package com.webank.weid.protocol.amop;

import com.webank.wedpr.assethiding.OwnerResult;
import lombok.Data;

import com.webank.weid.protocol.base.PresentationE;

/**
 * @author tonychen 2020年2月11日
 */
@Data
public class RequestZkpConsumableCredentialArgs {

    /**
     * user's credential list.
     */
    private PresentationE presentation;

    /**
     * user's ownerResult, generated by user's private key.
     */
    private OwnerResult ownerResult;

    /**
     * generated by verifier, related with policy id, target user weid, and challenge.
     */
    private String seqId;

    /**
     * original or zkp.
     */
    //private String credentialType;

    private String claim;
}
