package com.webank.weid.protocol.amop;

import java.util.Map;

import com.webank.wedpr.assethiding.OwnerResult;
import lombok.Data;

import com.webank.weid.protocol.base.PresentationE;

/**
 * @author tonychen 2020年2月6日
 */
@Data
public class RequestConsumableCredentialArgs {

    /**
     * user's credential list.
     */
    private PresentationE presentation;

    /**
     * user's ownerResult, generated by user's private key.
     */
    private OwnerResult ownerResult;

    /**
     * generated by verifier, related with policy id, target user weid, and challenge.
     */
    private String seqId;

    /**
     * original or zkp.
     */
    private String credentialType;
    
    /**
     * extra data which policy presenter can use it store some specific business data.
     */
    private Map<String, String> extra;
}
