package com.webank.weid.protocol.amop;

import com.webank.wedpr.assethiding.proto.CreditCredential;
import lombok.Data;

/**
 * @author tonychen 2020年2月6日
 */
@Data
public class TransferCreditCredentialArgs {

    /**
     * newly generated by user after transfering to verifier.
     */
    private CreditCredential creditCredential;
}
