package com.webank.weid.protocol.amop;

import lombok.Data;

import com.webank.weid.protocol.base.CredentialPojo;

/**
 * @author tonychen 2020年2月6日
 */
@Data
public class TransferCreditCredentialArgs {

    /**
     * newly generated by user after transfering to verifier.
     */
    private CredentialPojo consumableCredential;

    /**
     * generated by verifier, related with policyId, targetWeId, and challenge
     */
    private String seqId;
}
