package com.webank.weid.protocol.request;

import com.webank.weid.protocol.base.WeIdAuthentication;
import com.webank.weid.util.CredentialUtils;

import lombok.Data;

/**
 * @author tonychen 2020年2月11日
 *
 */
@Data
public class CreateZkpCredentialPojoArgs<T> {

	 /**
     * Required: The CPT type in standard integer format.
     */
    private Integer cptId;

    /**
     * Required: The issuer WeIdentity DID.
     */
    private String issuer;

    /**
     * Required: The expire date.
     */
    private Long expirationDate;

    /**
     * Required: The claim data.
     */
    private T claim;

    /**
     * Required: The private key structure used for signing.
     */
    private WeIdAuthentication weIdAuthentication;

    /**
     * Optional: The issuance date of the credential.
     */
    private Long issuanceDate = null;

    /**
     * 新增字段，issuer提前生成好的credential ID，对应credentialPojo里的ID.
     */
    private String id = null;

    /**
     * Optional:credential context.
     */
    private String context = CredentialUtils.getDefaultCredentialContext();
    
    /**
     * zkp related, generated by issuer.
     */
    private String issuerNonce;
    
    /**
     * zkp related, credential signature
     */
    private String credentialSignature;
}
