package com.webank.weid.protocol.request;

import java.util.List;

import com.webank.weid.constant.CredentialType;
import com.webank.weid.constant.TransportationType;
import com.webank.weid.protocol.base.CredentialPojo;
import com.webank.weid.protocol.base.PolicyAndChallenge;

import lombok.Data;

/**
 * @author tonychen 2020年2月10日
 *
 */
@Data
public class GetConsumableCredentialArgs {

	/**
	 * credentialPojoList user's credentialPojo list
	 */
	 private List<CredentialPojo> credentialPojoList;
	 
	 /**
	  * presentation policy and challenge, generated by verifier
	  */
	 private PolicyAndChallenge policyAndChallenge;
	 
	 /**
	  * target organization id.
	  */
	 private String toOrgId;
	 
	 /**
	  * credential type.
	  */
	 private CredentialType type;
	 
	 /**
	  * transport type.
	  */
	 private TransportationType transportationType;
}
